package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 27-Apr-2016 01:13:41 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AgentRol generated by hbm2java
 */
@Entity
@Table(name = "agent_rol", catalog = "tim12")
public class AgentRol implements java.io.Serializable {

	private Integer arId;
	private KorisnickiRacun korisnickiRacun;
	private Set<Rezervacija> rezervacijas = new HashSet<Rezervacija>(0);

	public AgentRol() {
	}

	public AgentRol(KorisnickiRacun korisnickiRacun) {
		this.korisnickiRacun = korisnickiRacun;
	}

	public AgentRol(KorisnickiRacun korisnickiRacun, Set<Rezervacija> rezervacijas) {
		this.korisnickiRacun = korisnickiRacun;
		this.rezervacijas = rezervacijas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AR_ID", unique = true, nullable = false)
	public Integer getArId() {
		return this.arId;
	}

	public void setArId(Integer arId) {
		this.arId = arId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KR_ID", nullable = false)
	public KorisnickiRacun getKorisnickiRacun() {
		return this.korisnickiRacun;
	}

	public void setKorisnickiRacun(KorisnickiRacun korisnickiRacun) {
		this.korisnickiRacun = korisnickiRacun;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agentRol")
	public Set<Rezervacija> getRezervacijas() {
		return this.rezervacijas;
	}

	public void setRezervacijas(Set<Rezervacija> rezervacijas) {
		this.rezervacijas = rezervacijas;
	}

}
