package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 05-May-2016 22:43:40 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Destinacija generated by hbm2java
 */
@Entity
@Table(name = "destinacija", catalog = "tim12")
public class Destinacija implements java.io.Serializable {

	private int destinacijaId;
	private String naziv;
	private Boolean omogucenPrevoz;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);

	public Destinacija() {
	}

	public Destinacija(int destinacijaId) {
		this.destinacijaId = destinacijaId;
	}

	public Destinacija(int destinacijaId, String naziv, Boolean omogucenPrevoz, Set<Hotel> hotels) {
		this.destinacijaId = destinacijaId;
		this.naziv = naziv;
		this.omogucenPrevoz = omogucenPrevoz;
		this.hotels = hotels;
	}

	@Id

	@Column(name = "DestinacijaID", unique = true, nullable = false)
	public int getDestinacijaId() {
		return this.destinacijaId;
	}

	public void setDestinacijaId(int destinacijaId) {
		this.destinacijaId = destinacijaId;
	}

	@Column(name = "Naziv", length = 100)
	public String getNaziv() {
		return this.naziv;
	}

	public void setNaziv(String naziv) {
		this.naziv = naziv;
	}

	@Column(name = "OmogucenPrevoz")
	public Boolean getOmogucenPrevoz() {
		return this.omogucenPrevoz;
	}

	public void setOmogucenPrevoz(Boolean omogucenPrevoz) {
		this.omogucenPrevoz = omogucenPrevoz;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinacija")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

}
