package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 28-Apr-2016 23:45:29 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Klijent generated by hbm2java
 */
@Entity
@Table(name = "klijent", catalog = "tim12")
public class Klijent implements java.io.Serializable {

	private Integer klijentId;
	private Osoba osoba;
	private Set<Rezervacija> rezervacijas = new HashSet<Rezervacija>(0);

	public Klijent() {
	}

	public Klijent(Osoba osoba) {
		this.osoba = osoba;
	}

	public Klijent(Osoba osoba, Set<Rezervacija> rezervacijas) {
		this.osoba = osoba;
		this.rezervacijas = rezervacijas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Klijent_ID", unique = true, nullable = false)
	public Integer getKlijentId() {
		return this.klijentId;
	}

	public void setKlijentId(Integer klijentId) {
		this.klijentId = klijentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Osoba_ID", nullable = false)
	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "klijent")
	public Set<Rezervacija> getRezervacijas() {
		return this.rezervacijas;
	}

	public void setRezervacijas(Set<Rezervacija> rezervacijas) {
		this.rezervacijas = rezervacijas;
	}

}
