package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 05-May-2016 22:43:40 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Klijent generated by hbm2java
 */
@Entity
@Table(name = "klijent", catalog = "tim12")
public class Klijent implements java.io.Serializable {

	private int klijentId;
	private Osoba osoba;
	private Set<Rezervacija> rezervacijas = new HashSet<Rezervacija>(0);

	public Klijent() {
	}

	public Klijent(int klijentId, Osoba osoba) {
		this.klijentId = klijentId;
		this.osoba = osoba;
	}

	public Klijent(int klijentId, Osoba osoba, Set<Rezervacija> rezervacijas) {
		this.klijentId = klijentId;
		this.osoba = osoba;
		this.rezervacijas = rezervacijas;
	}

	@Id

	@Column(name = "KlijentID", unique = true, nullable = false)
	public int getKlijentId() {
		return this.klijentId;
	}

	public void setKlijentId(int klijentId) {
		this.klijentId = klijentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OsobaID", nullable = false)
	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "klijent")
	public Set<Rezervacija> getRezervacijas() {
		return this.rezervacijas;
	}

	public void setRezervacijas(Set<Rezervacija> rezervacijas) {
		this.rezervacijas = rezervacijas;
	}

}
