package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 05-May-2016 22:43:40 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Korisnickiracunxrola generated by hbm2java
 */
@Entity
@Table(name = "korisnickiracunxrola", catalog = "tim12")
public class Korisnickiracunxrola implements java.io.Serializable {

	private Integer korisnickiRacunXrolaId;
	private Rola rola;
	private KorisnickiRacun korisnickiRacun;

	public Korisnickiracunxrola() {
	}

	public Korisnickiracunxrola(Rola rola, KorisnickiRacun korisnickiRacun) {
		this.rola = rola;
		this.korisnickiRacun = korisnickiRacun;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "KorisnickiRacunXRolaID", unique = true, nullable = false)
	public Integer getKorisnickiRacunXrolaId() {
		return this.korisnickiRacunXrolaId;
	}

	public void setKorisnickiRacunXrolaId(Integer korisnickiRacunXrolaId) {
		this.korisnickiRacunXrolaId = korisnickiRacunXrolaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RolaID")
	public Rola getRola() {
		return this.rola;
	}

	public void setRola(Rola rola) {
		this.rola = rola;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KorisnickiRacunID")
	public KorisnickiRacun getKorisnickiRacun() {
		return this.korisnickiRacun;
	}

	public void setKorisnickiRacun(KorisnickiRacun korisnickiRacun) {
		this.korisnickiRacun = korisnickiRacun;
	}

}
