package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 28-Apr-2016 23:45:29 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KorisnickiRacun generated by hbm2java
 */
@Entity
@Table(name = "korisnicki_racun", catalog = "tim12")
public class KorisnickiRacun implements java.io.Serializable {

	private Integer krId;
	private Osoba osoba;
	private String username;
	private String password;
	private Set<AgentRol> agentRols = new HashSet<AgentRol>(0);
	private Set<AdminRol> adminRols = new HashSet<AdminRol>(0);

	public KorisnickiRacun() {
	}

	public KorisnickiRacun(Osoba osoba) {
		this.osoba = osoba;
	}

	public KorisnickiRacun(Osoba osoba, String username, String password, Set<AgentRol> agentRols,
			Set<AdminRol> adminRols) {
		this.osoba = osoba;
		this.username = username;
		this.password = password;
		this.agentRols = agentRols;
		this.adminRols = adminRols;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "KR_ID", unique = true, nullable = false)
	public Integer getKrId() {
		return this.krId;
	}

	public void setKrId(Integer krId) {
		this.krId = krId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Osoba_ID", nullable = false)
	public Osoba getOsoba() {
		return this.osoba;
	}

	public void setOsoba(Osoba osoba) {
		this.osoba = osoba;
	}

	@Column(name = "Username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "korisnickiRacun")
	public Set<AgentRol> getAgentRols() {
		return this.agentRols;
	}

	public void setAgentRols(Set<AgentRol> agentRols) {
		this.agentRols = agentRols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "korisnickiRacun")
	public Set<AdminRol> getAdminRols() {
		return this.adminRols;
	}

	public void setAdminRols(Set<AdminRol> adminRols) {
		this.adminRols = adminRols;
	}

}
