package ba.unsa.etf.si.app.iTravel.DBModels;
//Generated 05-May-2016 22:43:40 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* Postavke generated by noke
*/
@Entity
@Table(name = "postavke", catalog = "tim12")
public class Postavke implements java.io.Serializable {

	private int postavkaId;
	private String nazivPostavke;
	private Boolean omoguceno;

	public Postavke() {
	}

	public Postavke(int postavkaId) {
		this.postavkaId = postavkaId;
	}

	public Postavke(int postavkaId, String nazivPostavke, Boolean omoguceno) {
		this.postavkaId = postavkaId;
		this.nazivPostavke = nazivPostavke;
		this.omoguceno = omoguceno;
	}

	@Id

	@Column(name = "PostavkaID", unique = true, nullable = false)
	public int getPostavkaId() {
		return this.postavkaId;
	}

	public void setPostavkaId(int postavkaId) {
		this.postavkaId = postavkaId;
	}

	@Column(name = "NazivPostavke", length = 45)
	public String getNazivPostavke() {
		return this.nazivPostavke;
	}

	public void setNazivPostavke(String nazivPostavke) {
		this.nazivPostavke = nazivPostavke;
	}

	@Column(name = "Omoguceno")
	public Boolean getOmoguceno() {
		return this.omoguceno;
	}

	public void setOmoguceno(Boolean omoguceno) {
		this.omoguceno = omoguceno;
	}

}
