package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 05-May-2016 22:43:40 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RezervisaniTerminSoba generated by hbm2java
 */
@Entity
@Table(name = "rezervisani_termin_soba", catalog = "tim12")
public class RezervisaniTerminSoba implements java.io.Serializable {

	private int rezervisaniTerminId;
	private Rezervacija rezervacija;
	private Soba soba;
	private Date datumPocetak;
	private Date datumKraj;
	private Boolean aktivan;

	public RezervisaniTerminSoba() {
	}

	public RezervisaniTerminSoba(int rezervisaniTerminId) {
		this.rezervisaniTerminId = rezervisaniTerminId;
	}

	public RezervisaniTerminSoba(int rezervisaniTerminId, Rezervacija rezervacija, Soba soba, Date datumPocetak,
			Date datumKraj, Boolean aktivan) {
		this.rezervisaniTerminId = rezervisaniTerminId;
		this.rezervacija = rezervacija;
		this.soba = soba;
		this.datumPocetak = datumPocetak;
		this.datumKraj = datumKraj;
		this.aktivan = aktivan;
	}

	@Id

	@Column(name = "RezervisaniTerminID", unique = true, nullable = false)
	public int getRezervisaniTerminId() {
		return this.rezervisaniTerminId;
	}

	public void setRezervisaniTerminId(int rezervisaniTerminId) {
		this.rezervisaniTerminId = rezervisaniTerminId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RezervacijaID")
	public Rezervacija getRezervacija() {
		return this.rezervacija;
	}

	public void setRezervacija(Rezervacija rezervacija) {
		this.rezervacija = rezervacija;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SobaID")
	public Soba getSoba() {
		return this.soba;
	}

	public void setSoba(Soba soba) {
		this.soba = soba;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DatumPocetak", length = 10)
	public Date getDatumPocetak() {
		return this.datumPocetak;
	}

	public void setDatumPocetak(Date datumPocetak) {
		this.datumPocetak = datumPocetak;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DatumKraj", length = 10)
	public Date getDatumKraj() {
		return this.datumKraj;
	}

	public void setDatumKraj(Date datumKraj) {
		this.datumKraj = datumKraj;
	}

	@Column(name = "Aktivan")
	public Boolean getAktivan() {
		return this.aktivan;
	}

	public void setAktivan(Boolean aktivan) {
		this.aktivan = aktivan;
	}

}
