package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 27-Apr-2016 01:13:41 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rezervacija generated by hbm2java
 */
@Entity
@Table(name = "rezervacija", catalog = "tim12")
public class Rezervacija implements java.io.Serializable {

	private Integer rezervacijaId;
	private AgentRol agentRol;
	private Klijent klijent;
	private Soba soba;
	private Date datumRezervacije;
	private Date pocetakTermina;
	private Date krajTermina;
	private Set<Racun> racuns = new HashSet<Racun>(0);

	public Rezervacija() {
	}

	public Rezervacija(AgentRol agentRol, Klijent klijent) {
		this.agentRol = agentRol;
		this.klijent = klijent;
	}

	public Rezervacija(AgentRol agentRol, Klijent klijent, Soba soba, Date datumRezervacije, Date pocetakTermina,
			Date krajTermina, Set<Racun> racuns) {
		this.agentRol = agentRol;
		this.klijent = klijent;
		this.soba = soba;
		this.datumRezervacije = datumRezervacije;
		this.pocetakTermina = pocetakTermina;
		this.krajTermina = krajTermina;
		this.racuns = racuns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Rezervacija_ID", unique = true, nullable = false)
	public Integer getRezervacijaId() {
		return this.rezervacijaId;
	}

	public void setRezervacijaId(Integer rezervacijaId) {
		this.rezervacijaId = rezervacijaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Agent_ID", nullable = false)
	public AgentRol getAgentRol() {
		return this.agentRol;
	}

	public void setAgentRol(AgentRol agentRol) {
		this.agentRol = agentRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Klijent_ID", nullable = false)
	public Klijent getKlijent() {
		return this.klijent;
	}

	public void setKlijent(Klijent klijent) {
		this.klijent = klijent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Soba_ID")
	public Soba getSoba() {
		return this.soba;
	}

	public void setSoba(Soba soba) {
		this.soba = soba;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Datum_rezervacije", length = 10)
	public Date getDatumRezervacije() {
		return this.datumRezervacije;
	}

	public void setDatumRezervacije(Date datumRezervacije) {
		this.datumRezervacije = datumRezervacije;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Pocetak_termina", length = 10)
	public Date getPocetakTermina() {
		return this.pocetakTermina;
	}

	public void setPocetakTermina(Date pocetakTermina) {
		this.pocetakTermina = pocetakTermina;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Kraj_termina", length = 10)
	public Date getKrajTermina() {
		return this.krajTermina;
	}

	public void setKrajTermina(Date krajTermina) {
		this.krajTermina = krajTermina;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rezervacija")
	public Set<Racun> getRacuns() {
		return this.racuns;
	}

	public void setRacuns(Set<Racun> racuns) {
		this.racuns = racuns;
	}

}
