package ba.unsa.etf.si.app.iTravel.DBModels;
// Generated 27-Apr-2016 01:13:41 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SlobodniTermini generated by hbm2java
 */
@Entity
@Table(name = "slobodni_termini", catalog = "tim12")
public class SlobodniTermini implements java.io.Serializable {

	private Integer slobodniId;
	private Termin termin;
	private Soba soba;

	public SlobodniTermini() {
	}

	public SlobodniTermini(Termin termin, Soba soba) {
		this.termin = termin;
		this.soba = soba;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Slobodni_ID", unique = true, nullable = false)
	public Integer getSlobodniId() {
		return this.slobodniId;
	}

	public void setSlobodniId(Integer slobodniId) {
		this.slobodniId = slobodniId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Termin_ID", nullable = false)
	public Termin getTermin() {
		return this.termin;
	}

	public void setTermin(Termin termin) {
		this.termin = termin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Soba_ID", nullable = false)
	public Soba getSoba() {
		return this.soba;
	}

	public void setSoba(Soba soba) {
		this.soba = soba;
	}

}
